compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# npmRegistryServer: "https://registry.npmmirror.com"

packageExtensions:
  "next-contentlayer@*":
    peerDependencies:
      next: "*"
  "contentlayer@*":
    peerDependencies:
      next: "*"
