import type { ThemeDefinition } from './types'

export const lightTheme: ThemeDefinition = {
  name: 'light',
  colorScheme: 'light',
  tokens: {
    colors: {
      background: '#f9f9f9',
      'background-muted': '#f0f2f5',
      surface: '#ffffff',
      'surface-elevated': '#ffffff',
      'surface-translucent': 'rgba(255, 255, 255, 0.88)',
      'surface-muted': '#f5f5f5',
      'surface-hover': '#f2f2f2',
      'surface-border': '#efefef',
      'surface-border-strong': '#e4e4e4',
      text: '#1f1f1f',
      heading: '#1f1f1f',
      'text-muted': '#747775',
      'text-subtle': '#8d908d',
      'text-inverse': '#ffffff',
      primary: '#3366ff',
      'primary-hover': '#4d7aff',
      'primary-muted': '#f0f4ff',
      'primary-border': '#d6e0ff',
      'primary-foreground': '#ffffff',
      accent: '#1f1f1f',
      'accent-muted': '#f0f2f5',
      'accent-foreground': '#1f1f1f',
      success: '#16a34a',
      'success-muted': '#dcfce7',
      'success-foreground': '#166534',
      warning: '#f59e0b',
      'warning-muted': '#fef3c7',
      'warning-foreground': '#92400e',
      danger: '#ef4444',
      'danger-muted': '#fee2e2',
      'danger-foreground': '#7f1d1d',
      info: '#3366ff',
      'info-muted': '#f0f4ff',
      'info-foreground': '#254edb',
      overlay: 'rgba(15, 23, 42, 0.45)',
      ring: '#c4b5fd',
      focus: 'rgba(124, 58, 237, 0.35)',
      divider: 'rgba(15, 23, 42, 0.08)',
      'badge-surface': '#e5e7eb',
      'badge-muted': '#f3f4f6',
      'badge-foreground': '#1f2937',
    },
    gradients: {
      'app-from': '#ede9fe',
      'app-via': '#f5f3ff',
      'app-to': '#e0f2fe',
      'primary-from': '#7c3aed',
      'primary-to': '#4c1d95',
    },
    shadows: {
      sm: '0 4px 8px rgba(0, 0, 0, 0.04)',
      md: '0 12px 32px rgba(15, 23, 42, 0.12)',
    },
    radii: {
      lg: '1rem',
      xl: '1.5rem',
      pill: '999px',
    },
  },
}

export default lightTheme
